### ISSUE TITLE
Export Control

### ISSUE THREAD

**Issue by mpredfearn** [WillCodeForCats/solaredge-modbus-multi#137] opened 2022-10-13 07:00 UTC
The export control block of registers allows control of how much power is exported from the system to the grid. This may be useful, for example, to prevent export if the export rate is negative.

Once the select / number controls are merged, it will be relatively easy to add support for this feature which should be the last one to bring this integration up to feature parity with https://github.com/binsentsu/home-assistant-solaredge-modbus (this was merged there in https://github.com/binsentsu/home-assistant-solaredge-modbus/pull/42)

**Comment by WillCodeForCats** [comment] 2022-10-13 13:43
I'm not 100% on this one because it can be used to violate a utility interconnect agreement, such as utilities that require zero export as part of being allowed to grid tie. And it's not always a money thing, at least in Hawaii I know they do this on segments that don't have appropriately sized transformers instead of forcing transformer upgrades like some utilities do.

It should probably be locked behind some kind of warning/disclaimer users have to agree to at minimum.

**Comment by mpredfearn** [comment] 2022-10-13 14:03
Totally agree - this feature must always be used in compliance with the connected utility rules. The way that https://github.com/binsentsu/home-assistant-solaredge-modbus (sort of) managed this was by not implementing the unlock sequence documented on page 15 of https://github.com/WillCodeForCats/solaredge-modbus-multi/blob/main/doc/Power-Control-Open-Protocol-for-SolarEdge-Inverters.pdf - i.e. to make use of the export control feature, the user has to manually write to the registers to enable this behaviour.
Although, for a system which is already configured with export limitation I presume that this functionality is already unlocked and so a user may be already to manipulate the Export Control Site Limit register? I don't know since I don't have such a system. Further input from other people required.

**Comment by purcell-lab** [comment] 2022-10-21 00:17
Zero export capability is an important feature for users who are exposed to wholesale market prices, which means the feed in price can go negative for a variable number of hours during the day. As the timing of the negative feed in is variable being able to switch this capability via HomeAssistant becomes very powerful.

I have 2x three phase 7kW inverters and Powerwall2 and am happy to assist with testing. I find myself switching between binsentsu:solaredge-modbus for the export control and this solaredge-modbus-multi for the multi inverter support ;-(

Last week in South Australia the negative feed in price was -$1.10/ kWh!

![310476885_10222616245539863_7205759744999278637_n](https://user-images.githubusercontent.com/79175134/197082132-2a1ab3d6-373b-468e-bce8-eeb3fd60882b.jpg)

**Comment by WillCodeForCats** [comment] 2022-10-21 01:13
I understand the purpose of it, but I want to implement it in a way that does not expose them by default and requires acknowledgement that altering these settings could be in violation of a utility agreement or cause a large bill if used improperly.

**Comment by purcell-lab** [comment] 2022-10-21 05:50
Thanks for 2.2.6-pre.1, my logs are reporting I_AdvPwrCtrlEn for both my inverters

```
$ grep I_AdvP home-assistant.log
2022-10-21 15:45:54.706 DEBUG (SyncWorker_7) [custom_components.solaredge_modbus_multi.hub] Inverter 1: I_AdvPwrCtrlEn 0x0
2022-10-21 15:45:55.834 DEBUG (SyncWorker_0) [custom_components.solaredge_modbus_multi.hub] Inverter 2: I_AdvPwrCtrlEn 0x0
2022-10-21 15:45:56.298 DEBUG (SyncWorker_3) [custom_components.solaredge_modbus_multi.hub] Inverter 1: I_AdvPwrCtrlEn 0x0
2022-10-21 15:45:57.326 DEBUG (SyncWorker_1) [custom_components.solaredge_modbus_multi.hub] Inverter 2: I_AdvPwrCtrlEn 0x0
```

**Comment by ThirstyDursty** [comment] 2022-10-21 09:02
> Totally agree - this feature must always be used in compliance with the connected utility rules. The way that https://github.com/binsentsu/home-assistant-solaredge-modbus (sort of) managed this was by not implementing the unlock sequence documented on page 15 of https://github.com/WillCodeForCats/solaredge-modbus-multi/blob/main/doc/Power-Control-Open-Protocol-for-SolarEdge-Inverters.pdf - i.e. to make use of the export control feature, the user has to manually write to the registers to enable this behaviour.
> Although, for a system which is already configured with export limitation I presume that this functionality is already unlocked and so a user may be already to manipulate the Export Control Site Limit register? I don't know since I don't have such a system. Further input from other people required.

Hypothetically how would one write these registers? :)

**Comment by WillCodeForCats** [comment] 2022-10-21 15:53
> Hypothetically how would one write these registers? :) speaking as someone from South Australia that is being charged an arm and leg because I can turn it down

I have been trying out different ideas in the UI, but nothing that can be released yet.

**Comment by ThirstyDursty** [comment] 2022-10-21 20:55
> > Hypothetically how would one write these registers? :) speaking as someone from South Australia that is being charged an arm and leg because I can turn it down
> 
> I have been trying out different ideas in the UI, but nothing that can be released yet.

Are they available settings in the commissioning process part of SetApp? In the SetApp they don’t show up in the settings. How would someone normally (technician) modify these values…they are after all in the documentation for use by installers and technicians

**Comment by purcell-lab** [comment] 2022-10-21 21:14
It looks so simple on the video:
https://youtu.be/Tt0tNX_1k-E

**Comment by ThirstyDursty** [comment] 2022-10-21 21:46
> It looks so simple on the video:
> https://youtu.be/Tt0tNX_1k-E

I can do that. Easy. Just put it in AP mode, connect to is wifi and then go to http://172.16.0.1/

Problem is getting HA to do it. As I have to be next to the unit to do it

**Comment by ThirstyDursty** [comment] 2022-10-21 22:33
> It looks so simple on the video:
> https://youtu.be/Tt0tNX_1k-E
Thought I was onto it…but won’t hold these settings either. Change and then 2min later it is back to default 
![42977C50-B918-4837-8E7E-0D175968B663](https://user-images.githubusercontent.com/98927039/197297984-a30c1ace-c7c9-41a5-8202-1ff2d1feb213.png)

**Comment by WillCodeForCats** [comment] 2022-10-23 16:08
This is what I came up with for a config dialog:

<img width="617" alt="Screen Shot 2022-10-23 at 9 02 12 AM" src="https://user-images.githubusercontent.com/48533968/197402710-8698f596-8326-49f5-83fb-8eb724c07ba9.png">

It would be accessed using a two step process through integration options, then an "advanced power control" checkbox, which if checked brings the user to this screen. Thoughts?

**Comment by purcell-lab** [comment] 2022-10-23 19:08
> It would be accessed using a two step process through integration options, then an "advanced power control" checkbox, which if checked brings the user to this screen. Thoughts

You are providing more context than the SetApp dialogue which I think is a good thing, but still allowing users to access the advanced settings.

**Comment by ThirstyDursty** [comment] 2022-10-23 20:07
> This is what I came up with for a config dialog:
> 
> <img alt="Screen Shot 2022-10-23 at 9 02 12 AM" width="617" src="https://user-images.githubusercontent.com/48533968/197402710-8698f596-8326-49f5-83fb-8eb724c07ba9.png">
> 
> It would be accessed using a two step process through integration options, then an "advanced power control" checkbox, which if checked brings the user to this screen. Thoughts?

Looks perfect…merg!!! 😂 the sun is rising

**Comment by WillCodeForCats** [comment] 2022-10-23 20:31
It's in branch `config-flow` but it doesn't actually do anything yet except act as a UI test.

**Comment by WillCodeForCats** [comment] 2022-10-25 05:18
I couldn't get the selectors to work properly in HA for some reason (they only worked from disabled->enabled but not the reverse) so the final version that's in PR #147 is checkboxes for each "enable" confirmation:

<img width="650" alt="Screen Shot 2022-10-24 at 10 17 45 PM" src="https://user-images.githubusercontent.com/48533968/197688657-dfb68db4-00b2-4bec-aede-f8701ef5bf44.png">

**Comment by purcell-lab** [comment] 2022-10-25 05:29
It might be good for compatibility with binsentsu to have similar controls:

![image](https://user-images.githubusercontent.com/79175134/197690148-04fc39a6-fa2b-4a74-8189-c6592792dd6d.png)


Export control limit mode
_select.solaredge_export_control_limit_mode_

![image](https://user-images.githubusercontent.com/79175134/197690176-81fc757a-1327-4e10-bfdf-a7221e5d3151.png)

Export Control Mode
_select.solaredge_export_control_mode

![image](https://user-images.githubusercontent.com/79175134/197689965-416e4855-bbf6-4cb6-a13c-723aeae6fc9a.png)

Export Control Site limit
_number.solaredge_export_control_site_limit_

![image](https://user-images.githubusercontent.com/79175134/197690080-8e6970f0-cd01-4d88-b4f5-3c1a027d4c0b.png)

**Comment by WillCodeForCats** [comment] 2022-10-26 16:29
issue closed in error

**Comment by Kahn** [comment] 2022-10-30 05:04
> Zero export capability is an important feature for users who are exposed to wholesale market prices, which means the feed in price can go negative for a variable number of hours during the day. As the timing of the negative feed in is variable being able to switch this capability via HomeAssistant becomes very powerful.
> 
> I have 2x three phase 7kW inverters and Powerwall2 and am happy to assist with testing. I find myself switching between binsentsu:solaredge-modbus for the export control and this solaredge-modbus-multi for the multi inverter support ;-(
> 
> Last week in South Australia the negative feed in price was -$1.10/ kWh!
> 
> ![310476885_10222616245539863_7205759744999278637_n](https://user-images.githubusercontent.com/79175134/197082132-2a1ab3d6-373b-468e-bce8-eeb3fd60882b.jpg)

We're seeing similar things here in NSW and after Amber broke their retailer level integration with Solaredge grid services API, it would be great to be plugging this with HA. Flipping circuit breakers off today to doge the negative FIT felt wrong in many ways. I just want zero export while still self consuming.

**Comment by WillCodeForCats** [comment] 2022-10-30 05:21
I need people to verify pymodbus 3.0.0 in Release v2.2.6-pre.3 runs ok since I'm not going to do any new or substantial updates to anything based on older pymodbus.

**Comment by purcell-lab** [comment] 2022-10-30 06:35
> I need people to verify pymodbus 3.0.0 in Release v2.2.6-pre.3 runs ok since I'm not going to do any new or substantial updates to anything based on older pymodbus.

2.2.6-pre.3 running solid for me. 2x three phase 7 kW inverters. Anything in particular you would like me to check?

Some minor transient issues, but probably more to do with my home network.

```
This error originated from a custom integration.

Logger: custom_components.solaredge_modbus_multi
Source: helpers/update_coordinator.py:151
Integration: SolarEdge Modbus Multi Device (documentation, issues)
First occurred: 9:22:18 AM (4 occurrences)
Last logged: 4:21:38 PM

Error fetching SolarEdge Coordinator data: Could not open Modbus/TCP connection to 192.168.86.100
Error fetching SolarEdge Coordinator data: Update failed: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```

**Comment by Kahn** [comment] 2022-10-30 11:05
So far so good here too after upgrading this afternoon. Two 1P inverters SE6000 and SE5000 follower with meter.

**Comment by WillCodeForCats** [comment] 2022-10-30 20:53
As long as it recovers from connection or update errors automatically without requiring a reload or restart to recover from, it should be fine. I'm looking for major errors where you have to restart home assistant or uncaught exceptions.

**Comment by purcell-lab** [comment] 2022-10-30 21:43
I got this one today with 2.2.6-pre.3.

Unsure if additional error handling is required.

```
This error originated from a custom integration.

Logger: custom_components.solaredge_modbus_multi
Source: custom_components/solaredge_modbus_multi/hub.py:684
Integration: SolarEdge Modbus Multi Device (documentation, issues)
First occurred: 6:39:24 AM (1 occurrences)
Last logged: 6:39:24 AM

Unexpected error fetching SolarEdge Coordinator data: 'ModbusIOException' object has no attribute 'exception_code'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/solaredge_modbus_multi/__init__.py", line 178, in _async_update_data
    return await self._hub.async_refresh_modbus_data()
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 329, in async_refresh_modbus_data
    await self._hass.async_add_executor_job(inverter.read_modbus_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 684, in read_modbus_data
    if inverter_data.exception_code == ModbusExceptions.IllegalAddress:
AttributeError: 'ModbusIOException' object has no attribute 'exception_code'
```

**Comment by WillCodeForCats** [comment] 2022-10-30 21:45
Yes that's the kinda of failures I'm looking for.

**Comment by WillCodeForCats** [comment] 2022-10-30 22:07
Fix will be in PR #148

**Comment by purcell-lab** [comment] 2022-10-31 00:46
Another odd one here:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:545
First occurred: 4:37:46 AM (2 occurrences)
Last logged: 7:31:35 AM

Updating state for sensor.solaredge_m1_imported_a_kwh (<class 'custom_components.solaredge_modbus_multi.sensor.ACEnergy'>) took 0.658 seconds. Please report it to the custom integration author.
Updating state for sensor.washing_machine_today_s_consumption (<class 'homeassistant.components.tplink.sensor.SmartPlugSensor'>) took 0.672 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tplink%22
```

**Comment by WillCodeForCats** [comment] 2022-11-01 16:26
[Release v2.2.6-pre.4](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.6-pre.4) is now available.

Assuming this corrects the problems in pre.4 I will make a 2.2.6 release then add storedge control.

**Comment by purcell-lab** [comment] 2022-11-01 23:14
Thanks I have downloaded pre.4 and can now see the Advanced Power Controls in the config flow.

Can you provide some further detail as to what options this chooses?

Direct Export/ indirect Export?

Also would it be possible for a select entity to enable dynamic control and setting the actual limitations in W? Per my comments at https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/137#issuecomment-1290004193


![Screenshot_20221102-090625](https://user-images.githubusercontent.com/79175134/199359385-b7ca7c51-7420-4b36-827c-e826827d1618.png)

**Comment by WillCodeForCats** [comment] 2022-11-01 23:15
They don't do anything at all yet.

**Comment by purcell-lab** [comment] 2022-11-01 23:22
Thanks

**Comment by WillCodeForCats** [comment] 2022-11-01 23:28
Once I have a final 2.2.6 release then I will release 2.2.7-pre.1 which will include PR #133, those control functions will be covered under the storedge control option.

You can set the options now and the related function will appear in a future release, but they will not enable any new functionality in 2.2.6.

**Comment by WillCodeForCats** [comment] 2022-11-03 19:43
[Release v2.2.7-pre.1](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.1) is now available.

**Comment by WillCodeForCats** [comment] 2022-11-07 06:37
Almost done with export limit controls, need another day or two to finish up for the next pre-release.

**Comment by WillCodeForCats** [comment] 2022-11-08 23:27
PR #179 adds export limit control.

<img width="504" alt="Screen Shot 2022-11-08 at 3 24 15 PM" src="https://user-images.githubusercontent.com/48533968/200697495-7b8dccb5-900a-41f5-ac0b-20b3781281fb.png">

The external production and negative site limit settings are disabled by default since it seems unlikely to me that anyone in a residential setting will need those, but they are available if needed.

**Comment by WillCodeForCats** [comment] 2022-11-10 16:55
[Release v2.2.7-pre.6](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.6) contains the limit controls PR

**Comment by WillCodeForCats** [comment] 2022-11-10 17:06
[Release v2.2.7-pre.7](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.7) adds export controls. Most of it says limit controls though because that's the naming SetApp uses, and I am preferring to use names that user facing things show.

**Comment by purcell-lab** [comment] 2022-11-10 18:58
Excellent, just loading up now and will be able to do some testing later today.

**Comment by purcell-lab** [comment] 2022-11-10 20:08
> Most of it says limit controls though because that's the naming SetApp uses, and I am preferring to use names that user facing things show.

In SetApp the Limit Control Mode options are:
- Export Control
- Production Control
- Minimum Input Control
- Disabled

![Screenshot_20221111-055306](https://user-images.githubusercontent.com/79175134/201193438-0011598a-2455-4510-bf28-01b31d26bb5f.png)

I see you have implemented a different set of modes:
- Disabled
- Export/ Import Meter
- Consumption Meter
- Production Limitation

![Screenshot_20221111-055835](https://user-images.githubusercontent.com/79175134/201193954-4584210c-5a95-4d83-8a8c-57a98ae0bca6.png)

Are these modes the same?

**Comment by WillCodeForCats** [comment] 2022-11-10 20:29
The selection modes in SetApp do not directly match what is available for control registers.

The control registers have two different mode options where SetApp shows a single "export" mode: "use a consumption meter" and "use a E+I meter". The difference should be which meter it will read to calculate the site limit (I presume this only matters if someone has both meter types otherwise the "best" type is an E+I meter so I would presume SetApp hides that logic and picks E+I first and consumption second).

Minimum input should be the same as negative export mode in registers, but as a non-exclusive flag that can coexist with either export meter mode and production control. In SetApp it appears as an exclusive option.

So In SetApp you have 3 distinct modes presented but in modbus there are more possible combinations.

**Comment by WillCodeForCats** [comment] 2022-11-10 20:44
It's also not clear for negative site limit setting if it signals that the site limit number should be treated as a negative internally or actually expects it to be set to a negative, because the description for the site limit value specifies positive numbers only. It can be changed to allow negative input but it's not clear what the proper behavior should be from the docs.

Unfortunately I can't test al the possible combinations personally since while my inverters do have all of those settings in SetApp, none of them expose the data over modbus.

**Comment by WillCodeForCats** [comment] 2022-11-10 20:46
After I made the release I thought the two export modes seemed unclear and changed the names in PR #181

**Comment by WillCodeForCats** [comment] 2022-11-10 20:57
Would these names be better?

* "Export Control (Export/Import Meter)"
* "Export Control (Consumption Meter)"
* "Production Control"

**Comment by purcell-lab** [comment] 2022-11-11 00:15
Core functionality seems to be working well.

You can see below I have set 0.0 W export and my two inverters are showing 86% & 80% active power limit and my actual export has dropped to a minor -27 W.

![image](https://user-images.githubusercontent.com/79175134/201232516-fc7ad9d3-1e25-4e95-ba38-12c3adcd3297.png)

**Comment by purcell-lab** [comment] 2022-11-11 00:18
I have received the occosinal error message when changing modes, the device goes unavailable for a couple of seconds and then comes back online.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/solaredge_modbus_multi/hub.py:478
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:34:42 AM (3 occurrences)
Last logged: 7:39:29 AM

[281472546293696] Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 109, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/solaredge_modbus_multi/number.py", line 352, in async_set_native_value
    await self._platform.write_registers(
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 1076, in write_registers
    await self.hub.write_registers(self.inverter_unit_id, address, payload)
  File "/config/custom_components/solaredge_modbus_multi/hub.py", line 478, in write_registers
    raise ModbusWriteError(result)
custom_components.solaredge_modbus_multi.hub.ModbusWriteError: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```

**Comment by purcell-lab** [comment] 2022-11-11 00:21
There seems to be an odd default site limit of -3.40282346638529e+38 W

![image](https://user-images.githubusercontent.com/79175134/201233354-95db30fe-1370-4af5-bfda-bb05b7556225.png)


![image](https://user-images.githubusercontent.com/79175134/201233276-dcaa069f-410d-4cf3-9844-fc846425b6e0.png)

**Comment by WillCodeForCats** [comment] 2022-11-11 00:32
Will work on cleaning it up a bit.

**Comment by WillCodeForCats** [comment] 2022-11-11 00:47
> Probably better names, but I'm unsure how the end user would choose between meters as they are unlikely to know which one they have installed.

It's on each meter device page:

<img width="341" alt="Screen Shot 2022-11-10 at 4 45 05 PM" src="https://user-images.githubusercontent.com/48533968/201236049-b9cf0a6c-db8a-4ae5-8038-27d4126d2fca.png">

So for now they'd just have to look, maybe in the future I can do something else.

**Comment by WillCodeForCats** [comment] 2022-11-11 02:21
Already handled in PR #181

**Comment by WillCodeForCats** [comment] 2022-11-11 02:22
Already handled in commit a80737213e89bb54c826c18a827f613ce324604a

**Comment by WillCodeForCats** [comment] 2022-11-11 21:47
Various fixes will be in PR #188

**Comment by WillCodeForCats** [comment] 2022-11-14 18:21
[Release v2.2.7-pre.8](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.8) is now available. It contains a large amount of changes to naming and validation for power control functions.

**Comment by WillCodeForCats** [comment] 2022-11-15 18:01
[Release v2.2.7-pre.9](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.9) fixes an issue on inverters that don't support power control functions over modbus.

**Comment by purcell-lab** [comment] 2022-11-16 06:40
Thanks installed 2.2.7-pre.9

The display is better and we no longer have that crazy value.

I am still seeing the device go unavailable briefly when changing modes and an error in the logs, but not much details.

I am trying to reduce export to zero, but it looks like it is now reducing total production to zero, pre.7 was limiting export correctly :-(

![image](https://user-images.githubusercontent.com/79175134/202103323-386251f1-af69-45e7-b100-66185d20f27e.png)

![image](https://user-images.githubusercontent.com/79175134/202103474-8b029289-a678-43fa-8a45-025c9962e0f6.png)


```
This error originated from a custom integration.

Logger: custom_components.solaredge_modbus_multi
Source: helpers/update_coordinator.py:182
Integration: SolarEdge Modbus Multi Device (documentation, issues)
First occurred: 5:26:29 PM (1 occurrences)
Last logged: 5:26:29 PM

Error fetching SolarEdge Coordinator data: Update failed: Meter read error: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```
```
2022-11-16 16:26:26.730 DEBUG (MainThread) [custom_components.solaredge_modbus_multi] Finished fetching SolarEdge Coordinator data in 6.727 seconds (success: True)
2022-11-16 16:26:29.730 DEBUG (SyncWorker_4) [custom_components.solaredge_modbus_multi.hub] Inverter 1 meter 1: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response rece
ived, expected at least 8 bytes (0 received)
2022-11-16 16:26:29.732 ERROR (MainThread) [custom_components.solaredge_modbus_multi] Error fetching SolarEdge Coordinator data: Update failed: Meter read error: Modbus Error: [Input/Output
] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
2022-11-16 16:26:29.733 DEBUG (MainThread) [custom_components.solaredge_modbus_multi] Finished fetching SolarEdge Coordinator data in 8.642 seconds (success: False)
```

**Comment by WillCodeForCats** [comment] 2022-11-16 15:18
There weren't any functional changes, only naming and validation cleanup. As far as I understand export site limit that's how its supposed to work: if any production exceeds consumption that would cause export in excess of the site limit value, production is throttled back to meet the site limit value. The limit control is described as "dynamically adjusts the PV power production in order to ensure that exported power does not exceed a preconfigured limit".

If an inverter is unresponsive (or a read cycle fails for any reason) entities go into unavailable state until the next successful polling cycle to prevent stale or invalid data from being displayed. This behavior was added in PR #38 (suggested in issue #23). In pre.9 updates were made to conform with existing behavior whereas the earlier pre-releases were incomplete.

If the inverter goes unresponsive after sending it a command I could add a config option to make the integration "sleep" after sending a command, then you can just put some value of 3-5 seconds for the sleep or whatever works for you. I can't actually do anything to fix the inverter going unresponsive.

**Comment by WillCodeForCats** [comment] 2022-11-16 18:22
Delay after sending a command option will be in PR #197 with a default of 3 seconds, config range is 0 to 10 seconds.

**Comment by WillCodeForCats** [comment] 2022-11-16 18:35
[Release v2.2.7-pre.10](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7-pre.10) includes the new delay option. I fast tracked this one and did very little testing on it, hopefully no bugs or regressions.

**Comment by purcell-lab** [comment] 2022-11-16 19:40
> There weren't any functional changes, only naming and validation cleanup. As far as I understand export site limit that's how its supposed to work: if any production exceeds consumption that would cause export in excess of the site limit value, production is throttled back to meet the site limit value. The limit control is described as "dynamically adjusts the PV power production in order to ensure that exported power does not exceed a preconfigured limit".

Thanks, the issue for me was it didn't appear to be limiting export to zero, it appeared to be limiting production to zero.

I will do some further testing today with pre.10 once the sun comes up.

**Comment by WillCodeForCats** [comment] 2022-11-16 19:52
Export limitation is a variable production limitation. The inverter(s) will dynamically adjust between 0% to 100% to seek the target site limit whenever consumption is less than production and there's nothing else to consume excess PV power such as charging a battery or other communicating device like the Smart EV Charger.

**Comment by WillCodeForCats** [comment] 2022-11-16 19:54
If it was in production limitation mode with a 0 site limit, it would have hard dropped to 0 and stayed there. The graphs show them dynamically adjusting and the integration can't do that.

**Comment by purcell-lab** [comment] 2022-11-16 20:09
With pre.10 the device seems to now go unavailable for a longer period when I change modes/ values.

This doesn't seem to impact functionality, but it just appears in the logs and lovelace.

```
2022-11-17 06:05:11.731 DEBUG (MainThread) [custom_components.solaredge_modbus_multi] Finished fetching SolarEdge Coordinator data in 5.730 seconds (success: True)
2022-11-17 06:05:14.734 DEBUG (SyncWorker_8) [custom_components.solaredge_modbus_multi.hub] Inverter 1: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, ex
pected at least 8 bytes (0 received)
2022-11-17 06:05:14.737 ERROR (MainThread) [custom_components.solaredge_modbus_multi] Error fetching SolarEdge Coordinator data: Update failed: No response from inverter ID 1
2022-11-17 06:05:14.739 DEBUG (MainThread) [custom_components.solaredge_modbus_multi] Finished fetching SolarEdge Coordinator data in 4.662 seconds (success: False)
2
```

**Comment by WillCodeForCats** [comment] 2022-11-16 20:49
You can try setting the Inverter Command Delay longer than 3 seconds. I don't have a reason for choosing 3 as the default.

**Comment by WillCodeForCats** [comment] 2022-11-16 21:16
Maybe the real question is if a default is even necessary. If the default is 0 (disabled) then if inverter response timeouts after sending commands is causing a problem then the user can adjust the delay to whatever works best for them. I don't know if inverters going silent after a command is normal or only happens on some setups.

**Comment by purcell-lab** [comment] 2022-11-16 21:59
Export Controls seem to be working as expected, I may have jumped the gun yesterday thinking it was limiting production to zero.

Thanks, I have setup to 10 seconds and it seems to fault less, but when it does fault it goes unavailable for 10 seconds ;-(

When using the binsentsu export controls the device didn't go unavailable which is my only other frame of reference.

**Comment by WillCodeForCats** [comment] 2022-11-16 22:14
> When using the binsentsu export controls the device didn't go unavailable which is my only other frame of reference.

Looks like that one just writes blind. It doesn't try to read or validate anything, no return checks, no error handling.

Here after a command is sent we immediately queue an update (if it was successful), but if the inverter is "busy" the update will time out on no response.

The other difference is the suggestion from #23 where we choose not to serve stale/bad data as a design choice and switch entities to unavailable until the next successful update.

**Comment by purcell-lab** [comment] 2022-11-17 02:27
I think going unavailable for a moment isn't a big issue. Maybe drop it to a warning rather than an error.

**Comment by WillCodeForCats** [comment] 2022-11-17 02:33
I can't change the log level of the coordinator update error since it's from HA core.

**Comment by purcell-lab** [comment] 2022-11-18 00:43
I have resolved what is going on when I set export limit to zero causing the system to reduce to zero production.

![image](https://user-images.githubusercontent.com/79175134/202589727-5cacc471-32f5-49ae-b0ae-8ed56154daa4.png)

I have an AC coupled battery (powerwall2) set to self consumption mode and an EV charging set to excess solar via ChargeHQ.  It would appear that both of these devices sense how much power is being exported and then adjust their consumption accordingly. Thus when I set SolarEdge to zero export both powerwall2 and chargehq see no export and so gradually reduce their consumption, which in turn is seen by SolarEdge as reduced load and thus it reduces production to maintain zero export. Finally the steady state is reached when I have zero export and zero production and the house is running 100% off the powerwall2 and there is no EV charging ;-(

By setting export limit to 200W, the steady state is excess solar EV charging is maximised, powerwall2 excess solar charging is maximised and I may lose a little bit in exports, but that's OK.

**Comment by WillCodeForCats** [comment] 2022-11-18 00:57
Glad to hear everything is working.

I'll let the pre.10 release bake a bit on my live system and watch for running errors over time, but unless something else comes up I think it is ready for a 2.2.7 release.

**Comment by ThirstyDursty** [comment] 2022-11-19 02:51
I have installed now...despite set-up I still don't have control.

I contacted Amber and had them unenroll me in grid services...I'm told that I have been...also had Solar Edge update my firmware.

Site Limit returned default a few seconds after changing....advanced power control remains off

**Comment by gferen** [comment] 2022-11-19 07:29
i just updated to latest version (i skipped few  in between)  and seems that there are some duplicated controls shown up. i am good with export control. since i dont have leagly set up PV station, i must be no export at all :)  but i like controlling betwen MSC mode and remote - to charge from PV only. Shortly disel generator will be added to system.
![image](https://user-images.githubusercontent.com/1295008/202839904-d894d870-f284-4b6d-a43f-461fdb6ff3f0.png)

p.s. @purcell-lab grat looking powerflow chart. would you mind sharing source? :)

**Comment by WillCodeForCats** [comment] 2022-11-19 17:12
Almost all unique IDs or names changed, which creates new entities. HA doesn't delete old entities, the user has to do that manually.

**Comment by WillCodeForCats** [comment] 2022-11-19 18:05
@ThirstyDursty I can add a control to try and change that value, but we is already has a very large number of changes so it'll have to be in the next release. I'll work on a 2.2.8 pre-release to add that control as soon as 2.2.7 is out.

**Comment by purcell-lab** [comment] 2022-11-19 20:45
> I have installed now...despite set-up I still don't have control.
> 
> I contacted Amber and had them unenroll me in grid services...I'm told that I have been...also had Solar Edge update my firmware.
> 
> Site Limit returned default a few seconds after changing....advanced power control remains off

@ThirstyDursty my site limit was constantly changing back everytime I set it because my solar inverter was still enrolled in Grid Services via SmartShift. It took me about a month to get Amber to process through SolarEdge with multiple follow-ups. I ended up with a guy in SolarEdge who could see everything and told me to keep going with Amber un-enroll process.  So I would go back to Amber and confirm your SolarEdge has been un-enrolled.

I have site limits working well here now, but the Advanced Power Control flag does not change.

Here is my automation, I chose a limit of 200 W export so my battery Self-Powered mode and ChargeHQ excess solar mode would both work:

```yaml
alias: Zero Export Automation
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.amber_feed_in_price
    below: 0
  - platform: numeric_state
    entity_id: sensor.amber_feed_in_price
    above: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.amber_feed_in_price
            below: 0
        sequence:
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: select
            entity_id: select.solaredge_i1_limit_control_mode
            type: select_option
            option: Export Control (Export/Import Meter)
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: number
            entity_id: number.solaredge_i1_site_limit
            type: set_value
            value: 200
    default:
      - device_id: 8e8f45345219e32b8a645ce8dfb767c3
        domain: select
        entity_id: select.solaredge_i1_limit_control_mode
        type: select_option
        option: Disabled
mode: single
```
![Screenshot_20221120-064451](https://user-images.githubusercontent.com/79175134/202870975-22620a8e-671a-41f7-a42c-2e22f10765b6.png)

**Comment by WillCodeForCats** [comment] 2022-11-28 17:46
[Release v2.2.7](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.7) is now available.

**Comment by WillCodeForCats** [comment] 2022-11-30 17:24
Now that we have a release with all the power control functions I'll go ahead and close this issue, but I've created discussion #207 with a reference back to here.

**Closed by WillCodeForCats** 2022-11-30 17:24 UTC
Labels: enhancement, help wanted
